### ISSUE TITLE
No Async Implementation

### ISSUE THREAD

**Issue by MrKevHunter** [Vonage/vonage-dotnet-sdk#126]
Your most recent implementation (3.2.2) does not use async to the client, and calling .Wait() (especially without ConfigureAwait() generally isn't seen as best practice.

Is there  a reason for no Async implementation?

**Comment by gagandeepp** [comment]
Is it still open?

**Comment by smikis** [comment]
Created PR for async implementation. Please tell me if it's missing something

**Comment by Huray-hub** [comment]
Hi! Is it still open? If it is, feel free to assign it to me!

**Comment by slorello89** [comment]
Hi @Huray-hub - @smikis has a PR open for this already :)

**Comment by Huray-hub** [comment]
> Hi @Huray-hub - @smikis has a PR open for this already :)

Oh, ok. If I could have seen it and didn't, then sorry. I'm new to open source contributing.
