### ISSUE TITLE
Incorrect enumeration of workflow

### ISSUE THREAD

**Issue by slorello89** [Vonage/vonage-dotnet-sdk#219]
https://github.com/Vonage/vonage-dotnet-sdk/blob/af1d91e31c0f4736c0c2a063ef78a101882f45a1/Vonage/Verify/VerifyRequest.cs#L10

Workflow 2 is marked as the workflow of 1 causing serialization issue - the same issue exists in:

https://github.com/Vonage/vonage-dotnet-sdk/blob/master/Vonage/Verify/Psd2Request.cs#L10

For more detail see the [developer portal](https://developer.nexmo.com/verify/guides/workflows-and-events)

**Comment by kzuri** [comment]
Hello @slorello89, can I help with this issue ?

**Comment by slorello89** [comment]
Yep feel free to!

**Comment by kzuri** [comment]
@slorello89 have a look at this 😄

**Comment by slorello89** [comment]
This issue is resolved by #227
