### ISSUE TITLE
Enhancements to the ISmsClient

### ISSUE THREAD

**Issue by slorello89** [Vonage/vonage-dotnet-sdk#222]
[ISmsClient](https://github.com/Vonage/vonage-dotnet-sdk/blob/master/Vonage/Messaging/ISmsClient.cs) currently only has 1 method which accepts a `SendSmsRequest` object. It would be nice to add overloads to this to support the most common use cases (e.g. just sending a flat text message from a number to a number - skipping the initialization of a separate request object)

The new signature will look something like this:

`SendSmsResponse SendAnSms(string to, string from, string text, SmsType type = SmsType.text, credentials = null);`

**Comment by guctum** [comment]
@slorello89 hey can I snag this?

**Comment by slorello89** [comment]
Hi @guctum - feel free!

**Comment by guctum** [comment]
@slorello89 clarification question: implemented in SmsClient.cs, is there any specific business logic the overload needs? Or should it take similar logic as the original?

**Comment by slorello89** [comment]
It's performing the same function - it's just a specific (and very common Usecase). the idea is that it saves the user from having to initialize the SendSmsRequest object.

**Comment by slorello89** [comment]
This Item was resolved in v5.6.2 - much thanks to paul for all his help!
