### ISSUE TITLE
Generate Signature Secret for test Inbound SMS And ValidateSignature

### ISSUE THREAD

**Issue by baroved1** [Vonage/vonage-dotnet-sdk#244]
I have tried to generate signature(sig) from your library – for test my webhook and validate signature.
But I got invalid signature.
I attached my unit test code, What Am I doing wrong ?
I think the data that i send as the first param to GenerateSignature method, it is wrong.
Thanks!
![1](https://user-images.githubusercontent.com/78050926/105916952-6ee80080-603a-11eb-8f22-4d8ff1849458.PNG)
![2](https://user-images.githubusercontent.com/78050926/105916957-70192d80-603a-11eb-8853-d98de36a3dec.PNG)

**Comment by slorello89** [comment]
Hi  @baroved1 - you're using the `GenerateSignature` method incorrectly, that should probably be an internal method - but essentially what it's doing is taking a string that is compliant with the format laid out in our [guide](https://developer.nexmo.com/concepts/guides/signing-messages) and generating a signature from it. The inbound message structure provided by the SDK can actually [generate](https://github.com/Vonage/vonage-dotnet-sdk/blob/master/Vonage/Messaging/InboundSms.cs#L74) the string for you out of the inbound message object.

**Comment by baroved1** [comment]
So, How Can I generate signature for testing my webhook?
I would like to write unit testing...

**Comment by slorello89** [comment]
https://github.com/Vonage/vonage-dotnet-sdk/blob/master/Vonage.Test.Unit/MessagingTests.cs#L340 - This is how I test it.

**Comment by baroved1** [comment]
Thank you , It works for me !
