### ISSUE TITLE
Migrate Shorts Code 2FA API to SMS API using 10 DLC

### ISSUE THREAD

**Issue by troyvnit** [Vonage/vonage-dotnet-sdk#250]
Hi,

I have implemented the 2FA using client.ShortCode.RequestTwoFactorAuth for 2 years. Few days ago I received an email about 10 DLC migration needed. But I am unable to find good docs / examples to keep our 2FA flow. I already checked the Vonage Verify API but it will impact to whole system on both mobile and backend. So, my question is:
Is there any guide to replace client.ShortCode.RequestTwoFactorAuth with new Vonage SMS API? 

Thank you!

**Comment by dragonmantank** [comment]
Please keep in mind 10DLC is only replacing the Shared Short Code numbers. If you are using a Dedicated Short Code, you will be fine. Carriers are only removing access to shared codes.

The new 10DLC restrictions is not actually an entirely new API, but a registration system for long virtual numbers (the regular 10 digit geographic numbers). 10DLC allows you to register a geographic number for many of the same use cases that shared short codes were commonly used for, but this is more of a book-keeping step the carriers are imposing than a huge technical change.

We will be working on migration guides and more documentation as it gets closer to the actual cutoff dates, but carriers are still working on how this functions themselves. You can go ahead and register your brand and a 2FA campaign on your dashboard right now though, which will give you the rate limits and if you account is able to run 2FA campaigns.

## Sending the SMS

For sending the 2FA message, you will need to use the normal SMS API. You will just send a normal SMS message (example [here](https://developer.nexmo.com/messaging/sms/code-snippets/send-an-sms/dotnet) instead.

```c#
verificationCode = // logic to generate a 4-6 digit number randomly;
var response = VonageClient.SmsClient.SendAnSms(new Vonage.Messaging.SendSmsRequest()
{
    To = TO_NUMBER,
    From = VONAGE_BRAND_NAME,
    Text = "Your verification code is: " + verificationCode
});
```
This will send the SMS to the user that they can supply to your application like normal. You will need to store that verification number temporarily in something like a database to look up when the user actually enters the pin later in your workflow.

## Handling Opt-in/Opt-out

This is something new you will need to handle on your own. Opt-in will generally be handled by your application already (it should be fine that a new user signs up and you collect their number to send a 2FA request to), but you will need to handle keywords like "STOP" manually. You will need to configure an incoming SMS webhook on the 2FA number and parse the incoming message for the "STOP" keyword (example [here](https://developer.nexmo.com/messaging/sms/code-snippets/receiving-an-sms/dotnet)).

```c#
[HttpGet("webhooks/inbound-sms")]        
public IActionResult InboundSms()
{            
    var sms = WebhookParser.ParseQuery<InboundSms>(Request.Query);
    Console.WriteLine($"SMS Received with message: {sms.Text}");
    return NoContent();
}
```
