### ISSUE TITLE
v5.7.0 doesn't support the latest changes in Number Insight API

### ISSUE THREAD

**Issue by AndrewGorstcheruk** [Vonage/vonage-dotnet-sdk#252]
### General description of the issue or question
v5.7.0 doesn't support the latest changes in Number Insight API: 
If roaming is unknown there is a change in the JSON structure:
Old response:
"roaming": { "status": "unknown"}
New response:
"roaming": "unknown"
If roaming value is roaming (aka true) then nothing changes between the old code and the new code.

### Which target framework(s) of .NET can you reproduce this issue against?
.NET Framework 4.8

### What operating system(s) is exhibiting this issue?
Windows Server 2008 R2

### Version or commit hash
v5.7.0
 
### Expected Behavior
Get StandardInsightResponse

### Actual Behavior
> Newtonsoft.Json.JsonSerializationException: Error converting value "unknown" to type 'Vonage.NumberInsights.Roaming'. Path 'roaming', line 26, position 24.
>   Source    : Newtonsoft.Json
>   TargetSite: System.Object EnsureType(Newtonsoft.Json.JsonReader, System.Object, System.Globalization.CultureInfo, Newtonsoft.Json.Serialization.JsonContract, System.Type)
>   StackTrace:
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    at Vonage.Request.ApiRequest.SendGetRequest[T](Uri uri, AuthType authType, Credentials creds)
>    at Vonage.NumberInsights.NumberInsightClient.GetNumberInsightStandard(StandardNumberInsightRequest request, Credentials creds)

> System.ArgumentException: Could not cast or convert from System.String to Vonage.NumberInsights.Roaming.
>   Source    : Newtonsoft.Json
>   TargetSite: System.Object EnsureTypeAssignable(System.Object, System.Type, System.Type)
>   StackTrace:
>    at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
>    at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)

### Steps to Reproduce
public StandardInsightResponse GetPhoneNumberInfo(string number)
{
	var config = _dataManager.GetIntegrationConfig(VonageSettings.VonageConfigId);
	var cred = new Credentials(config.Login, config.Password)
	{
		AppUserAgent = Configuration.Instance.Settings[USER_AGENT],
		ApplicationId = config.Token1,
		ApplicationKey = File.ReadAllText(AppDomain.CurrentDomain.BaseDirectory + VonageSettings.VonagePrivateKey)
	};
	var client = new VonageClient(cred);
	var results = client.NumberInsightClient.GetNumberInsightStandard(new StandardNumberInsightRequest()
	{
		Number = number
	});
	return results;
}

**Comment by slorello89** [comment]
Hi @AndrewGorstcheruk - this issue is resolved by #251 and the release of v5.8.0 - thank you for pointing this out!
