### ISSUE TITLE
Vonage.Request.VonageHttpRequestException- Vonage.Request.ApiRequest Error during Call Transfer

### ISSUE THREAD

**Issue by ahmedCareAngel** [Vonage/vonage-dotnet-sdk#254]
I don't know if  the below referenced issue is the same , but  I am hoping i can get to the bottom if this intermittent issue when transferring calls it happens less than 10% of transfers:

outerMessage
Response status code does not indicate success: 400 (Bad Request). Json from error: {"type":"BAD_REQUEST","error_title":"Bad Request"}

outerAssembly
Vonage, Version=5.3.0.0, Culture=neutral, PublicKeyToken=null

 Vonage.Voice.VoiceClient.UpdateCall","level":9,"line":0}, "message":"Response status code does not indicate success: 400 (Bad Request). Json from error: {\"type\":\"BAD_REQUEST\",\"error_title\":\"Bad Request\"}","severityLevel":"Error","type":"Vonage.Request.VonageHttpRequestException"," ]

_Originally posted by @sk2andy in https://github.com/Vonage/vonage-dotnet-sdk/issues/71#issuecomment-412791508_

okay, wanna give you some feedback because I got it to work. I downloaded the repo and modified it because to my mind this library has a problem:
Your destination member in a CallEditCommand is a string. That is kind of a problem because when it comes to a transfer of a call the destination is a complex object. So the json is always malformed when I set the destination (either via a dynamic or my own NexmoDestination-Class that has `public static implicit operator string(NexmoDestination destination)`)
```
{
	"action": "transfer",
	"destination": "{\"type\":\"ncco\",\"url\":[\"https://e2344168.ngrok.io/api/nexmo/handover?callId=1070ceafd03de77feb7c62ffc69af54d&from=4912345678961\"]}"
}
```
what I needed was:
```
{
	"action": "transfer",
	"destination": {
		"type": "ncco",
		"url": ["https://e2344168.ngrok.io/api/nexmo/handover?callId=1070ceafd03de77feb7c62ffc69af54d&from=4912345678961"]
	}
}
```
I think you should change the type of destination from string to a specific Destination-Object because whit the quotes no one can pass a complex object to the destination. Or am I missing something?

**Comment by matt-lethargic** [comment]
Hey @ahmedCareAngel sorry for the VERY long reply, we normally try not to leave things this long. I've been looking at the issue and the fix that you mentioned. I can't see this as being the same issue as the fix mentioned by @sk2andy was implemented a long time ago and we have tests that cover this situation.

What would be really useful is if you could get the payload logs for the calls that have an issue. This would mean setting the Log Level to "Debug". The library will then log all URIs and JSON Payloads that are sent. If you are getting 400 Bad Request it could be that some information that is required in the UpdateCall method is missing from your side when you've created the `CallEditCommand` 

For information on how to setup the logging see the read me https://github.com/Vonage/vonage-dotnet-sdk#logging

If you have solved the issue I'd love to hear how you fixed it or indeed what the problem actually was. (I'll get you a response a bit quicker next time, promise!)

**Comment by matt-lethargic** [comment]
Closing as no reply from OP
