### ISSUE TITLE
VonageClient.SmsClient.SendAnSmsAsync unit test: "The type initializer for 'Vonage.Configuration' threw an exception."

### ISSUE THREAD

**Issue by surexxx** [Vonage/vonage-dotnet-sdk#306]
Trying to write an XUnit unit test to test the integration. Unfortunately VonageClient.SmsClent.SendAnSmsAsync method threw a TypeInitializationException when initialize Vonage.Configuration.
<img width="647" alt="image" src="https://user-images.githubusercontent.com/18722513/207011572-64e6ed41-ddf5-4eb3-b469-c2c7091cf7c0.png">
The InnerException is a MethodNotFoundException:
Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.Object> Microsoft.Extensions.Configuration.IConfigurationBuilder.get_Properties()'.
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/18722513/207011871-aa29325a-7d08-4f6c-a04c-9b88ddda2bb8.png">
What I am missing? Is the SDK capable to run under XUnit framework?

Code to reproduce:
```csharp
            VonageClient client = new VonageClient(
                Credentials.FromApiKeyAndSecret(
                    Config.ApiKey, 
                    Config.ApiSecret)
            );

            // Send sms request
            SendSmsRequest smsRequest = new SendSmsRequest
            {
                From = Config.From,
                To = "your phone number",
                Text = "test message",
                Type = SmsType.Text,
                Callback = "https://<your callback url>",
                Ttl = 30000
            };

            SendSmsResponse smsResponse = await client.SmsClient.SendAnSmsAsync(smsRequest);

```

**Comment by Tr00d** [comment]
Hi @surexxx,
Thanks for contributing so much recently 😄 
I remember you posted this one on the community Slack already, and I actually replied two months ago. 
So, the SDK does run well with xUnit. It is the main testing framework used in our test project. That's definitely an odd problem you got there. I remember finding [this post](https://stackoverflow.com/questions/12745985/c-method-not-found-exception-setter-missing) on SO which looks like a similar problem. You may have an older version of the DLL in the cache maybe.
Please give it a try. On my end, I'll try to reproduce the problem.

**Comment by surexxx** [comment]
Hi @Tr00d , sorry I didn't see your comment in slack channel. I'll check it. The issue is still exists.

**Comment by surexxx** [comment]
Hi @Tr00d , 
finally the source of the issue is discovered. There was a version mismatch between Microsoft.Extensions.Configuration (3.1.29) and Microsoft.Extensions.Configuration.Json (1.1.2). After updating the last one the same version as other (3.1.29) the issue has gone and the unit test run as expected, without any exception.
<img width="347" alt="image" src="https://user-images.githubusercontent.com/18722513/213208271-e2a879d5-6840-4bf0-be52-eb4429e21914.png">
