### ISSUE TITLE
Please add RetrieveSubAccounts method

### ISSUE THREAD

**Issue by hyounoo** [Vonage/vonage-dotnet-sdk#419]
**Is your feature request related to a problem? Please describe.**
Currently only RetrieveSubAccount and RetrieveSubAccountAsync method provided.

Please add RetrieveSubAccountsAsync that returns list of subAccount

**Describe the solution you'd like**
Please add RetrieveSubAccounts method that supports pagination.

**Comment by Tr00d** [comment]
Hi @hyounoo,
Thanks for pointing that out. Indeed, we do not cover all the features (yet?) for SubAccounts. The main reason is the current implementation is a contribution from a community member.
I'll check where we stand on that in the next couple of days. I'll make sure to get back to you asap.
Obviously, same stuff for https://github.com/Vonage/vonage-dotnet-sdk/issues/421.

**Comment by Tr00d** [comment]
Hi @hyounoo,
I'm following up on my previous message. The good news is, with SubAccounts going GA, I will implement these features in my current sprint.
I will be able to work on it next week, followed by a release (6.4.0).
I'll keep you posted.

**Comment by hyounoo** [comment]
> Hi @hyounoo, I'm following up on my previous message. The good news is, with SubAccounts going GA, I will implement these features in my current sprint. I will be able to work on it next week, followed by a release (6.4.0). I'll keep you posted.

That's good news!

Also I've tried bunch of apis including accountapi, numbersapi, etc
Most of them has some issue with authentication.
Please check that too

Thanks in advance

**Comment by Tr00d** [comment]
> > Hi @hyounoo, I'm following up on my previous message. The good news is, with SubAccounts going GA, I will implement these features in my current sprint. I will be able to work on it next week, followed by a release (6.4.0). I'll keep you posted.
> 
> That's good news!
> 
> Also I've tried bunch of apis including accountapi, numbersapi, etc Most of them has some issue with authentication. Please check that too
> 
> Thanks in advance

Indeed, I noticed a problem with BasicAuth and published a fix last week (v6.3.3). Were you using that version?

**Comment by hyounoo** [comment]
> Indeed, I noticed a problem with BasicAuth and published a fix last week (v6.3.3). Were you using that version?

Yeah, I was hoping the last release would solve the issue, but it didn't :(
![image](https://github.com/Vonage/vonage-dotnet-sdk/assets/9585318/ef9803c9-b72a-42e0-980c-1518bf74dabc)

**Comment by Tr00d** [comment]
Okay, I'm going to look that up today

**Comment by hyounoo** [comment]
> Okay, I'm going to look that up today

Let me know if you need specific apis that I've tried and had auth issue

**Comment by Tr00d** [comment]
@hyounoo I just tried to create/retrieve a subaccount using v6.3.3, and it's working as expected.

![image](https://github.com/Vonage/vonage-dotnet-sdk/assets/59444272/3b54054a-75ac-4018-992d-6c57d9b7dd37)
![image](https://github.com/Vonage/vonage-dotnet-sdk/assets/59444272/3cb4139a-a39d-4828-b588-9c43986560fa)
![image](https://github.com/Vonage/vonage-dotnet-sdk/assets/59444272/81917635-bff2-4fb0-aa94-a8c9388fac6e)

Same goes for NumbersAPI.

![image](https://github.com/Vonage/vonage-dotnet-sdk/assets/59444272/b6da196a-9cbb-4eeb-a246-46b15ff84355)
![image](https://github.com/Vonage/vonage-dotnet-sdk/assets/59444272/c8b20792-54bf-4475-b0fa-0b214c3078b3)

Can you confirm? 
We've had a case before where an older package version was used from the cache (not saying it's specifically that - just giving a lead).

**Comment by hyounoo** [comment]
That could be the case
Thank for informing
I will try clear the cache and retry

**Comment by hyounoo** [comment]
@Tr00d 
Just confirmed CreateSubAccountAsync and RetrieveSubAccountAsync apis works but with extra apikey param
```cs
var response = await _vonageClient.AccountClient.CreateSubAccountAsync(createSubAccountRequest, vonageApiKey);
var response = await _vonageClient.AccountClient.RetrieveSubAccountAsync(subAccountKey, vonageApiKey);
```

without extra apikey param it would return 404 (Not Found)

Since vonageClient with factoryMethod would inject apiKey and secret, this can be ommited?

**Comment by Tr00d** [comment]
Yup, the extra ApiKey param is actually mandatory 🤦 
I do not know why it was set up as an optional parameter. In fact, it could have been optional if the ApiKey was taken from the credentials.

https://github.com/Vonage/vonage-dotnet-sdk/blob/da9075af12da2f6953e3fb46bcb7f65cc7eb7616/Vonage/Accounts/AccountClient.cs#L44C1-L50

**Comment by hyounoo** [comment]
> Yup, the extra ApiKey param is actually mandatory 🤦 I do not know why it was set up as an optional parameter. In fact, it could have been optional if the ApiKey was taken from the credentials.
> 
> https://github.com/Vonage/vonage-dotnet-sdk/blob/da9075af12da2f6953e3fb46bcb7f65cc7eb7616/Vonage/Accounts/AccountClient.cs#L44C1-L50

Yep the line 48 should take the creds.apiKey if apiKey = null
```cs
public SubAccount CreateSubAccount(CreateSubAccountRequest request, string apiKey = null, 
     Credentials creds = null) => 
     new ApiRequest(creds ?? this.Credentials).DoRequestWithJsonContent<SubAccount>( 
         HttpMethod.Post, 
         ApiRequest.GetBaseUri(ApiRequest.UriType.Api, $"/accounts/{apiKey ?? creds.ApiKey}/subaccounts"), 
         request, 
         AuthType.Basic 
     ); 
```

but this again broke when both creds and apiKey are null

If apiKey param is there to distinguish subAccount from mainAccount, I think it is better to check creds presence because main account's apiKey and secret will used for authenticate anyway.

If the method requires authentication, it should assume creds is not null and validate if not provided when called.

**Comment by hyounoo** [comment]
> 

It's kinda urgent but I can wait if the sdk can be properly implemented and sort out the mess if there's any.

Thanks for your support.

Appreciated.

**Comment by Tr00d** [comment]
Alright, let me see what I can do.

**Comment by hyounoo** [comment]
@Tr00d 
Just let let you know
The critical method
```cs
var response = await _vonageClient.NumbersClient.BuyANumberAsync(numberTransactionRequest);

return response;
```

returning 401 and preventing further implementation.

If its ok, this method would be the first one I want to see working.

Thank you

**Comment by hyounoo** [comment]
> I ran a similar piece on my end, which works. ![image](https://user-images.githubusercontent.com/59444272/244424506-0ae69e61-e59c-4322-aba4-e82bfca485c2.png) ![image](https://user-images.githubusercontent.com/59444272/244424621-27e0c291-e0b6-4dc5-87fa-8e01d98c1423.png)
> 
> Did you provide an ApiKey/Secret couple in the credentials? Was it from a SubAccount? If so, I don't know if it works and try from the main account.

There was apiKey property in the request model and I provided main account apiKey
I will try without apiKey in the request body
Thanks for confirming

**Comment by hyounoo** [comment]
@Tr00d Just tried and it works without subAccount apikey 
Thanks for letting me know
Hope subAccount gets buyNumber availability soon too

**Comment by Tr00d** [comment]
Well, at least you got it working for now. I'm about to release a new version today with a fix for the SubAccount features ([here](https://github.com/Vonage/vonage-dotnet-sdk/pull/426)).
As far as I know, buying a number directly from a SubAccount is impossible. But you can buy one from the main account and then transfer it to a SubAccount. More details [here](https://developer.vonage.com/en/api/subaccounts#transferNumber)

**Comment by hyounoo** [comment]
> Well, at least you got it working for now. I'm about to release a new version today with a fix for the SubAccount features ([here](https://github.com/Vonage/vonage-dotnet-sdk/pull/426)). As far as I know, buying a number directly from a SubAccount is impossible. But you can buy one from the main account and then transfer it to a SubAccount. More details [here](https://developer.vonage.com/en/api/subaccounts#transferNumber)

Oh thanks, that's a good news

**Comment by Tr00d** [comment]
FYI - [v6.4.0](https://github.com/Vonage/vonage-dotnet-sdk/releases/tag/v6.4.0) is now available. It fixes the optional ApiKey issue, as we discussed previously.
I'll get back to you regarding the whole SubAccount implementation in the upcoming week.

**Comment by hyounoo** [comment]
@Tr00d 👍 
Thanks for the quick release!

**Comment by Tr00d** [comment]
Hi @hyounoo,

[v6.5.0](https://github.com/Vonage/vonage-dotnet-sdk/releases/tag/v6.5.0) has been released today. It contains the implementation of all SubAccounts features mentioned in our [API Reference](https://developer.vonage.com/en/api/subaccounts).

Please note that they're available on another client: `SubAccountsClient` instead of `AccountsClient`. If you'd like to see an example of how to use the client, feel free to take a look at our [code snippets](https://github.com/Vonage/vonage-dotnet-code-snippets/tree/master/DotNetCliCodeSnippets/SubAccounts).

**Comment by hyounoo** [comment]
@Tr00d nice!!!
Can’t wait see it

**Comment by hyounoo** [comment]
@Tr00d this Match lamda method is confusing

How should I return the success object of Account here?
```cs
var message = response.Match(
            success => $"SubAccount created - {success.ApiKey}",
            failure => $"SubAccount creation failed: {failure.GetFailureMessage()}");
```

**Comment by Tr00d** [comment]
So, the `response` object is a `Result<T>`. It's a Monad that can be either a `Success` or a `Failure`. When using `.Match()` to extract (and/or transform) the value, you must provide one operation for each state (or scenario). 
What do you want to do if the SubAccount creation fails? 

You can find explanations [here](https://github.com/Vonage/vonage-dotnet-sdk#monads). There's also a section explaining [how to work with them if you don't want to use Monads](https://github.com/Vonage/vonage-dotnet-sdk#what-if-you-dont-want-to-use-monads). TL;DR: a `GetSuccessUnsafe` method will throw an exception if the Monad is in a `Failure` state.
