### ISSUE TITLE
Converation API

### ISSUE THREAD

**Issue by hyounoo** [Vonage/vonage-dotnet-sdk#432]
**Is your feature request related to a problem? Please describe.**
I would like to use this sdk for creating Converations, members and users.

In order to generate jwt for our customers, we need to create a conversation and user through rest api.

It is doable through cURL and Node.js but not with this SDK

https://developer.vonage.com/en/conversation/code-snippets/conversation/create-conversation
https://developer.vonage.com/en/conversation/code-snippets/member/create-member
https://developer.vonage.com/en/conversation/code-snippets/user/create-user

**Describe the solution you'd like**
Please implement conversation client and methods.

**Comment by Tr00d** [comment]
Hi @hyounoo,
Conversations API is still in beta - AFAIK beta products are not meant to be exposed through the SDK.
I'll double-check internally and ask about the roadmap for this product.
Cheers

**Comment by hyounoo** [comment]
@Tr00d Thanks for letting me know.

How about user token creation?

I've found JWT generation method in Vonage sdk but the format was not compatible ex) til was not form of GUID and so on...

I would like to have user creation and issuing authentication token supported from SDK.

Although I've implmented above with curl, It would be better if the sdk supports them.

Thanks

**Comment by Tr00d** [comment]
There are three ways (too many IMO) to create a token from the SDK.
You can use either a couple ApplicationId/PrivateKey, or a Credentials object containing ApplicationId/PrivateKey.

```csharp
// 1
 string token = Jwt.CreateToken(applicationId, privateKey);
 var generator = new Jwt();
// 2
 Result<string> token = generator.GenerateToken(credentials);
// 3
 Result<string> token = generator.GenerateToken(applicationId, privateKey);
```

**Comment by Tr00d** [comment]
Hi @hyounoo,

I was able to chase that one internally. 
For the moment, Conversation Api isn't scheduled on our roadmap. Unfortunately, I cannot give a forecast for a potential implementation.
It doesn't mean you can't use this Api - but you'll have to implement the call yourself. As mentioned in my previous post, you can use the token generation from the SDK.
