### ISSUE TITLE
Running in Azure Functions host crashes runtime

### ISSUE THREAD

**Issue by sdgroeneveld** [Vonage/vonage-dotnet-sdk#451]
Microsoft.Azure.WebJobs.Script: Error building configuration in an external startup class. Microsoft.Azure.Functions.Extensions: Method not found: 'Microsoft.Extensions.Configuration.IConfigurationBuilder Microsoft.Azure.WebJobs.Hosting.IWebJobsConfigurationBuilder.get_ConfigurationBuilder()'.

and

Value cannot be null. (Parameter 'provider') on local debug. Azure functions host failed to start.

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
Tested on Azure functions v4 with .NET 6.0, used VS CODE.

We'll just use the REST option for now.

**Comment by Tr00d** [comment]
Hi @sdgroeneveld,
Thanks for the feedback. I'll try to reproduce the issue on my end.
Can you tell me which version of the SDK you're using? Can you share a snippet of the failing code?

**Comment by Tr00d** [comment]
I found similar issues [here](https://stackoverflow.com/questions/68231946/net-core-3-azure-function-method-not-found-iwebjobsconfigurationbuilder-get-c) and [there](https://stackoverflow.com/questions/66790036/functionsstartup-vs-iwebjobsstartup-problems-reading-httpheaders-on-the-request)

**Comment by Tr00d** [comment]
Closed as no feedback received.
