### ISSUE TITLE
Avoid upgrading Moq | Replace by another lib

### ISSUE THREAD

**Issue by Tr00d** [Vonage/vonage-dotnet-sdk#485]
Due to recent [privacy issues](https://github.com/moq/moq/issues/1372), the following is required:
- Avoid upgrading Moq. The malware version (4.20.0) have been removed from the nuget repository, the latest version (4.20.2) looks safe.
- Replace Moq by another library. This is definitely a trust concern. The good news is Moq is not used in latest implementations (WireMock is), so this move forward over time.

**Comment by SimonPriceUL** [comment]
@Tr00d 4.20.2 I think is also unsafe, stay on 4.18.4 if youre keeping Moq

![image](https://github.com/Vonage/vonage-dotnet-sdk/assets/121941606/fd96cc4f-237f-4800-8688-9f23754c3cb8)

**Comment by Tr00d** [comment]
@SimonPriceUL Thanks for letting me know. I'll definitely keep an eye on this. My main goal is to remove Moq entirely as I don't really need it. This is for the 'legacy' side of things
