### ISSUE TITLE
ConversationAction does not support custom event url

### ISSUE THREAD

**Issue by MarcusKohnert** [Vonage/vonage-dotnet-sdk#561]
**Describe the bug**
The class [ConversationAction](https://github.com/Vonage/vonage-dotnet-sdk/blob/e60d8de6a978a598acb16b03ebe0365c53cac3c5/Vonage/Voice/Nccos/ConversationAction.cs#L8) provides the two properties [EventMethod](https://github.com/Vonage/vonage-dotnet-sdk/blob/e60d8de6a978a598acb16b03ebe0365c53cac3c5/Vonage/Voice/Nccos/ConversationAction.cs#L46) and [EventUrl](https://github.com/Vonage/vonage-dotnet-sdk/blob/e60d8de6a978a598acb16b03ebe0365c53cac3c5/Vonage/Voice/Nccos/ConversationAction.cs#L52) to customize the webhook where events should be received. If those values are set they are not respected during runtime and according to Vonage support team the Conversation action does not support an eventUrl.

***Original text by Vonage support team:***
'The Conversation action does not support an eventUrl for the events of a conversation, only for the recording. You can find further information in our documentation: https://developer.vonage.com/en/voice/voice-api/ncco-reference#conversation

For inbound calls, you will need to specify the eventUrl at the application level, and can override this for specific actions. For outbound calls, you can override the application eventUrl in the API request.'

Support request: [#2410685](https://api.support.vonage.com/hc/requests/2410685)

**Environment(please complete the following information):**
 - .NET Runtime [e.g. .NET7] 
 - SDK Version [e.g. v6.14.0]

**Comment by Tr00d** [comment]
Hi @MarcusKohnert,

Thanks for letting me know - I'll have a look at that.
Based on my understanding, those properties should not be there in the first place. I need to ensure they're not used elsewhere, or at least that this action isn't used for more than it should. 
On my side, this is clearly a breaking change as I'm modifying a public contract. I guess you can expect that to be fixed in the upcoming major release 7.0.0.

I'll keep you posted.

**Comment by Tr00d** [comment]
Hi @MarcusKohnert,

I wanted to share some feedback. This breaking change is available in the latest version [v7.0.0-alpha](https://github.com/Vonage/vonage-dotnet-sdk/releases/tag/v7.0.0-alpha).
Being an alpha, the package is still subject to potential problems. I do expect a final version very soon.

**Comment by Tr00d** [comment]
Hi,

[v7.0.0](https://github.com/Vonage/vonage-dotnet-sdk/releases/tag/v7.0.0) is finally out, and this problem has been addressed.

Don't hesitate to share some feedback :smile:

**Comment by MarcusKohnert** [comment]
Hi @Tr00d,

I'm a bit surprised to still find [EventMethod](https://github.com/Vonage/vonage-dotnet-sdk/blob/7e0b5dad1989553c639d9c3e68f81e19947e51fc/Vonage/Voice/Nccos/ConversationAction.cs#L46) and [EventUrl](https://github.com/Vonage/vonage-dotnet-sdk/blob/7e0b5dad1989553c639d9c3e68f81e19947e51fc/Vonage/Voice/Nccos/ConversationAction.cs#L52) on class ConversationAction.

Didn't the change make it to v7? 🤔

**Comment by Tr00d** [comment]
Hi @MarcusKohnert,

You're absolutely right... I need to investigate how this happened.
Apologies for that :disappointed: 

I'll find a solution to release it. I guess I can deprecate/remove the current v7.X.X version, and make a new one the normal breaking upgrade.
Anyway, I'll manage.

**Comment by Tr00d** [comment]
@MarcusKohnert,

After investigation, I lost track of that change. It wasn't included in the alpha version, despite my message.
My bet is the branch got deleted before being merged. It doesn't look great...

Anyway, I released v7.2.0 this morning and unlisted prior v7.1.0 and v7.0.0 as this change was documented in the migration guide. I know I'm "bending" the laws of semantic versioning but it seems to be the past of least resistance at the moment.

Sorry about all that fuss.

**Comment by MarcusKohnert** [comment]
No worries. 🤗 I can confirm, that the properties are now removed. ✅
