### ISSUE TITLE
VerifyClient.VerifyRequestAsync hangs when called in an asp.net 4.7 application

### ISSUE THREAD

**Issue by tim-arheit** [Vonage/vonage-dotnet-sdk#574]
When calling var result =    await client.VerifyClient.VerifyRequestAsync(req, _credentials).ConfigureAwait(false);
The task simply never returns. It does successfully call the verify API   as I do get a text message.

After downloading the vonage-dotnet-sdk to troubleshoot it,  I found numerous awaits in VerifyClient.cs and ApiRequest did not have a .ConfigureAwait(false);  (which can in certain cases cause a task to wait indefinitely)  After fixing all those cases and VerifyRequestAsync, and VerifyCheckAsync both returned as expected.

I didn't test the other API methods, but I suspect many of them also have the same issue.

**Comment by Tr00d** [comment]
Yes, indeed - you're absolutely correct.

I investigated that topic earlier today and I learned that it's recommended to use `ConfigureAwait` when working on a library, given you don't know if the caller is going to need the synchronization context or not. So, it's better to leave that open, knowing there are rare cases where you can have a deadlock... For what I've seen, it's mostly with ASP.NET.

I'll tackle that problem. Hopefully, some automated refactoring can take care of that for me.

**Comment by Tr00d** [comment]
@tim-arheit The version [7.2.1](https://github.com/Vonage/vonage-dotnet-sdk/releases/tag/v7.2.1) has been released and should solve this problem.

Can you give it a try and let me know if everything's okay on your side?

**Comment by tim-arheit** [comment]
7.2.1 does fix the issue we were having.
Thanks!

**Comment by Tr00d** [comment]
Great to hear! :)
