### ISSUE TITLE
SmsResponseMessage.cs is missing parameter.

### ISSUE THREAD

**Issue by fahadhabib80** [Vonage/vonage-dotnet-sdk#577]
**Bug Description**
In SmsResponseMessage.cs class, there should be AccountRef and ClientRef properties. However Client Ref is missing and Account Ref comments are mentioned to have client-ref value, which is incorrect. This bug means we cannot match Sms Response with original request in async situation as once a response came back, we dont know which original request it belongs to. Hence client-ref match is needed.

**Expected behaviour**
New property ClientRef needs to be added. See screenshot.

**Screenshots**
![client-ref](https://github.com/Vonage/vonage-dotnet-sdk/assets/73715395/8b9cf087-87c3-4db5-99bc-ea054b26f70a)

**Code snippets**
n/a

**Environment(please complete the following information):**
v7.2.0 SDK release

**Additional context**
none

**Comment by fahadhabib80** [comment]
Vonage API ref [https://developer.vonage.com/en/api/sms?source=messaging](url)

![client-ref2](https://github.com/Vonage/vonage-dotnet-sdk/assets/73715395/7b7f890e-fc52-420b-83c6-0a0eb7a7389b)

**Comment by Tr00d** [comment]
Hi @fahadhabib80,

Thanks for raising this one out. 
I find it odd that this property is missing because that API didn't change in a while. It's actually the legacy API to send SMS; we always recommend customers to favor MessagesAPI instead.

I'll get back to you as soon as there's progress on this.

**Comment by fahadhabib80** [comment]
Hi @Tr00d 

Thanks for picking it up. I did not realise that Message API is also for SMS. I looked and picked SMS API by default. As dev is still actively done on this, so assumption is that it will supported in near future. I could switch to Message API if that's the direction of travel from Vonage

Thanks

**Comment by Tr00d** [comment]
Messages API supports multiple carriers, including SMS. Don't get me wrong - SMS API is going to stay for a long time but we tend to recommend people to use Messages, if possible, for multiple reasons:
* SMS API is considered legacy as it still only supports Basic Auth, while Messages supports Bearer Auth.
* Messages API is the one receiving the most updates and upgrades.

**Comment by Tr00d** [comment]
Hi @fahadhabib80 ,

This has been fixed in the latest version, [v7.2.2](https://github.com/Vonage/vonage-dotnet-sdk/releases/tag/v7.2.2).

Let me know if it works out for you.

**Comment by Tr00d** [comment]
Closing issue after two weeks. Don't hesitate to reach out if yoou face any problem.

**Comment by fahadhabib80** [comment]
Apologies for not making any comments here. It worked well for my use case. 

Thanks for quick fix.
