### ISSUE TITLE
Vonage Video Session Monitoring

### ISSUE THREAD

**Issue by jcharro1979** [Vonage/vonage-dotnet-sdk#578]
In Vonage Video session monitoring, it is necessary to identify the source of events. According to the documentation at https://developer.vonage.com/en/video/guides/session-monitoring#connection-created, information is expected to be provided in the 'data' property, as described in https://developer.vonage.com/en/video/guides/create-token#connection-data. For example, **userId** should be included. However, in our tests, the 'data' property always arrives empty.

**Expected behaviour**
The **userId** or any other claims passed during token creation should be received in the events, allowing the backend to identify where the event occurs.

Token with new **userId** claim
![image](https://github.com/Vonage/vonage-dotnet-sdk/assets/39131072/d1104847-c7ab-47bc-ae6b-7f1ab74f2abe)

**connectionCreated** event with data property empty.
![image](https://github.com/Vonage/vonage-dotnet-sdk/assets/39131072/249ac849-1ac3-43cf-9322-1ff419921e4e)

**Comment by Tr00d** [comment]
Hi @jcharro1979,

Thanks for letting me know.
I'll have a look and get back to you asap.

**Comment by Tr00d** [comment]
@jcharro1979,

So, the problem is you used a `userId` key to set your value. There's no explicit link between `userId` and `data`.
If you want to pass that information to the callback response, you need to assign the `userId` to a `connection_data` claim in the token.

For example:
```json
{
   "iat": xxx,
   "applicatoinId": xxx,
   "jti": xxx,
   "role": xxx,
   "session_id": xxx,
   "scope": xxx,
   "connection_data": {yourUserId},
}
```

Can you give it a try and let me know?

**Comment by jcharro1979** [comment]
Hello @Tr00d:

Thank you very much for your response, I have completed tests and I already obtain the user information in the callback event.

![image](https://github.com/Vonage/vonage-dotnet-sdk/assets/39131072/298dbfbb-bce7-47ea-baf6-35e91fbeffdd)

![image](https://github.com/Vonage/vonage-dotnet-sdk/assets/39131072/73e853e6-49d1-4a04-9398-c5ba13abd135)

However, I think that the documentation should be updated, since this claim `connection_data` is not specified.

Thank you very much

Greetings

**Comment by Tr00d** [comment]
@jcharro1979,

Absolutely, I went through the same struggle you did so I asked the documentation to be improved.
Also, I think I'll try to make this obvious (as a feature) in the SDK as well.
