### ISSUE TITLE
Commit fd02cd5  Remove EventUrl and EventMethod from ConversationAction

### ISSUE THREAD

**Issue by jbNACATI** [Vonage/vonage-dotnet-sdk#579]
We use these properties in production, they are in the Vonage docs: " You can override the default recording event URL and default HTTP method by providing custom eventUrl and eventMethod options in the conversation action definition."

Possible to add them back to .NET client or confirm that this functionality will stop working in the future?

**Comment by Tr00d** [comment]
Hi @jbNACATI,
Thanks for raising that one. It is clearly a mistake.
I plan to publish a new version in the following days, I'll keep you informed.
Our documentation is not explicit enough on that matter - I'll make sure to adapt it as well.

**Comment by Tr00d** [comment]
@jbNACATI,

A new version, [v7.6.0](https://github.com/Vonage/vonage-dotnet-sdk/releases/tag/v7.6.0), is available which restores 'eventUrl' and 'eventMethod'.
Let me know if everything's good on your side.

**Comment by jbNACATI** [comment]
Thanks perfect.  Everything is good!
