### ISSUE TITLE
Invalid Token Error when creating Session.

### ISSUE THREAD

**Issue by Selonka** [Vonage/vonage-dotnet-sdk#593]
**Describe the bug**
Invalid Token Error when creating Session.

**To Reproduce**
Create a Vonage Client, with credentials (api-key and secret). 

Call:
```
await m_Client.VideoClient.SessionClient.CreateSessionAsync(CreateSessionRequest
            .Build()
            .WithLocation("192.168.1.1")
            .WithMediaMode(MediaMode.Routed)
            .WithArchiveMode(ArchiveMode.Manual)
            .Create());
```

**Expected behaviour**
Successfully Create a Session with api-key and secret.

**Environment(please complete the following information):**
 - .net Freame work 4.6.2
 - Nuget Package Vonage Version 7.9.0

**Additional context**
Calling GetAppliactionAsync via ApplicationClient works fine for me.

**Comment by Tr00d** [comment]
Hi @Selonka,

Thanks for reaching out. Sadly, it's not an issue - Video API doesn't support basic authentication (see [our specs](https://developer.vonage.com/en/api/video#session-create)). Also, here's our documentation page on [how to create a session](https://developer.vonage.com/en/video/guides/create-session?source=video).

Basically, you need to create an application in the Developer Dashboard, and enable Video capabilities. Onward, you'll be able to provide AppId/PrivateKey for authentication.

Hope my answer was clear enough.

**Comment by Tr00d** [comment]
Closing that issue.
