### ISSUE TITLE
Can't use custom template id in StartVerificationRequest

### ISSUE THREAD

**Issue by allegg-tipalti** [Vonage/vonage-dotnet-sdk#597]
**Describe the bug**
According to Verify API V2 the StartVerificationRequest has an option to send a template_id field. However, although the SDK supports custom templates (create/update/etc) the StartVerificationRequest doesn't support a builder of that kind and there is no other way to send that field other than a direct call to the API using an http request.

**To Reproduce**
Search GitHub project or the package of the SDK when added a .net solution.

**Expected behaviour**
Since the documentation clearly states that the template_id can be sent in the StartVerificationRequest and the custom templates are supported in the latest version of the SDK I believe that the template_id field should also be supported in the StartVerificationRequest object and have a dedicated IOptionalBuilder.

**Screenshots**
No screenshots available.

**Code snippets**
There is no code other than the code of the request object in the SDK.

**Environment(please complete the following information):**
 - .NET 8.0
 - SDK Version 7.10.0

**Comment by Tr00d** [comment]
Hi @allegg-tipalti,

Thanks for raising that issue.
Indeed, that property is missing for SMS and WhatsApp. It was introduced recently, but isn't part of the SDK yet. 

I will try to deliver it in short notice, and keep you posted.

Cheers
